"""
Markdown report generator — produces fleet-visible evolution reports.

Generates a structured markdown document suitable for committing
to a fleet-visible location (e.g. message-in-a-bottle/for-fleet/).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


def generate_fleet_report(
    timeline: list,
    metrics: Any,
    agent_matrix: Optional[Dict[str, Dict[str, Any]]] = None,
    milestones: Optional[list] = None,
    bottlenecks: Optional[List[str]] = None,
    dependency_graph: Optional[Dict[str, List[str]]] = None,
) -> str:
    """Generate a comprehensive fleet evolution report as markdown.

    Parameters
    ----------
    timeline : list
        TimelineEvent objects (or any with timestamp, category, repo,
        agent, description, significance attributes).
    metrics : FleetMetrics
        The computed fleet metrics.
    agent_matrix : dict, optional
        Output of MetricsComputer.agent_contribution_matrix().
    milestones : list, optional
        Significant timeline events.
    bottlenecks : list of str, optional
        Identified bottleneck descriptions.
    dependency_graph : dict, optional
        repo -> [repos] dependency mapping.
    """
    sections: List[str] = []
    sections.append(_header())
    sections.append(_overview(metrics, timeline))
    if milestones:
        sections.append(_timeline_highlights(milestones))
    if agent_matrix:
        sections.append(_agent_contributions(agent_matrix))
    sections.append(_repo_health(timeline, metrics))
    if dependency_graph:
        sections.append(_dependency_section(dependency_graph))
    if bottlenecks:
        sections.append(_bottlenecks(bottlenecks))
    sections.append(_recommendations(metrics, bottlenecks))
    sections.append(_footer())

    return "\n\n".join(sections)


# ------------------------------------------------------------------
# Section generators
# ------------------------------------------------------------------

def _header() -> str:
    return (
        "# FLUX Fleet Evolution Report\n\n"
        "> Auto-generated by flux-evolution tracker.\n"
        "> *\"If you can't see the evolution, you can't improve it.\"*\n"
    )


def _overview(metrics: Any, timeline: list) -> str:
    try:
        m = metrics.as_dict()
    except Exception:
        m = {
            "total_repos": getattr(metrics, "total_repos", 0),
            "total_commits": getattr(metrics, "total_commits", 0),
            "active_agents": getattr(metrics, "active_agents", 0),
            "cross_agent_commits": getattr(metrics, "cross_agent_commits", 0),
            "test_coverage_ratio": getattr(metrics, "test_coverage_ratio", 0.0),
            "spec_completeness": getattr(metrics, "spec_completeness", 0.0),
        }

    lines = [
        "## Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total repos tracked | {m['total_repos']} |",
        f"| Total commits | {m['total_commits']} |",
        f"| Active agents | {m['active_agents']} |",
        f"| Cross-agent commits | {m['cross_agent_commits']} |",
        f"| Test coverage ratio | {m['test_coverage_ratio']:.0%} |",
        f"| Spec completeness | {m['spec_completeness']:.0%} |",
    ]
    return "\n".join(lines)


def _timeline_highlights(milestones: list) -> str:
    lines = ["## Timeline Highlights", ""]
    for i, ev in enumerate(milestones[:20], 1):
        ts = getattr(ev, "timestamp", "")
        cat = getattr(ev, "category", "")
        agent = getattr(ev, "agent", "")
        desc = getattr(ev, "description", "")
        sig = getattr(ev, "significance", 1)
        stars = "\u2605" * sig + "\u2606" * (5 - sig)
        lines.append(f"**{i}.** [{ts}] `{cat}` — {agent}: {desc}  {stars}")
    return "\n".join(lines)


def _agent_contributions(matrix: Dict[str, Dict[str, Any]]) -> str:
    lines = [
        "## Agent Contributions",
        "",
        "| Agent | Commits | Repos | Top Category |",
        "|-------|---------|-------|-------------|",
    ]
    for agent, data in sorted(matrix.items(), key=lambda x: -x[1].get("commits", 0)):
        commits = data.get("commits", 0)
        repos = data.get("repos", 0)
        cats = data.get("categories", {})
        top_cat = max(cats, key=cats.get) if cats else "—"
        lines.append(f"| {agent} | {commits} | {repos} | {top_cat} |")
    return "\n".join(lines)


def _repo_health(timeline: list, metrics: Any) -> str:
    """Summarise per-repo activity."""
    from collections import Counter
    repo_counts: Counter = Counter()
    repo_agents: Dict[str, set] = {}

    for ev in timeline:
        repo = getattr(ev, "repo", "")
        agent = getattr(ev, "agent", "")
        if repo:
            repo_counts[repo] += 1
            repo_agents.setdefault(repo, set()).add(agent)

    lines = [
        "## Repo Health",
        "",
        "| Repo | Commits | Agents | Status |",
        "|------|---------|--------|--------|",
    ]
    for repo, count in repo_counts.most_common():
        agents = repo_agents.get(repo, set())
        agent_count = len(agents)
        if count >= 5 and agent_count >= 2:
            status = "\U0001f7e2 Active"
        elif count >= 2:
            status = "\U0001f7e1 Moderate"
        else:
            status = "\U0001f534 Low"
        short_repo = repo.split("/")[-1] if "/" in repo else repo
        lines.append(f"| {short_repo} | {count} | {agent_count} | {status} |")
    return "\n".join(lines)


def _dependency_section(graph: Dict[str, List[str]]) -> str:
    lines = ["## Dependency Graph", ""]
    if not graph:
        lines.append("No inter-repo dependencies detected.")
        return "\n".join(lines)

    lines.append("```")
    for source, targets in sorted(graph.items()):
        for target in targets:
            lines.append(f"{source} -> {target}")
    lines.append("```")
    return "\n".join(lines)


def _bottlenecks(bottlenecks: List[str]) -> str:
    lines = ["## Bottlenecks", ""]
    if not bottlenecks:
        lines.append("No bottlenecks identified — fleet is healthy.")
        return "\n".join(lines)

    for i, issue in enumerate(bottlenecks, 1):
        lines.append(f"{i}. \u26a0\ufe0f {issue}")
    return "\n".join(lines)


def _recommendations(metrics: Any, bottlenecks: Optional[List[str]]) -> str:
    lines = ["## Recommendations", ""]
    recs: List[str] = []

    try:
        test_cov = metrics.test_coverage_ratio
    except Exception:
        test_cov = 0.0
    try:
        cross = metrics.cross_agent_commits
    except Exception:
        cross = 0

    if test_cov < 0.15:
        recs.append(
            "**Increase test coverage**: Add conformance test vectors "
            "to under-tested repos, especially new ones."
        )
    if cross < 3:
        recs.append(
            "**Boost cross-agent collaboration**: Use message-in-a-bottle "
            "to request PR reviews from other fleet agents."
        )
    if bottlenecks:
        recs.append(
            f"**Address {len(bottlenecks)} bottleneck(s)** identified above "
            "to improve fleet velocity."
        )
    if not recs:
        recs.append(
            "Fleet is in good shape. Continue monitoring for emerging patterns."
        )

    for i, r in enumerate(recs, 1):
        lines.append(f"{i}. {r}")
    return "\n".join(lines)


def _footer() -> str:
    return (
        "---\n\n"
        "*Generated by flux-evolution. "
        "See [flux-evolution repo](https://github.com/SuperInstance/flux-evolution) for details.*"
    )
